/**
 * Type definitions for architecture visualization feature.
 *
 * This module defines two core data structures:
 * 1. RepoInventory - Deterministic analysis output from ts-morph
 * 2. ClusterGraph - LLM-generated clustering of files into architectural components
 */

// ============================================================================
// RepoInventory - Deterministic Analysis Output
// ============================================================================

/**
 * Complete inventory of a repository's structure and dependencies.
 * Generated by ArchitectureAnalysisService from AST parsing.
 */
export interface RepoInventory {
	files: FileRecord[] // All analyzed TypeScript/JavaScript files
	dependencies: DependencyEdge[] // file→file import graph
	metadata: InventoryMetadata
}

/**
 * Record of a single analyzed file with exports and imports.
 */
export interface FileRecord {
	path: string // Relative to workspace root
	size: number // Bytes
	linesOfCode: number
	exports: ExportedSymbol[] // Functions, classes, types exported
	imports: ImportRecord[] // What this file imports
	language: "typescript" | "javascript"
}

/**
 * A symbol exported from a file (function, class, interface, etc.)
 */
export interface ExportedSymbol {
	name: string
	kind: "function" | "class" | "interface" | "type" | "const" | "enum" | "variable"
	isDefault: boolean
}

/**
 * Import statement parsed from a file.
 */
export interface ImportRecord {
	source: string // Module path (relative or package)
	resolvedPath?: string // Resolved file path (if local)
	importedSymbols: string[] // What's imported
	isTypeOnly: boolean
}

/**
 * Directed edge representing a file→file dependency.
 */
export interface DependencyEdge {
	from: string // Source file path
	to: string // Target file path
	count: number // Number of import statements
	importedTypes: string[] // Symbol kinds imported
}

/**
 * Metadata about the analysis run.
 */
export interface InventoryMetadata {
	timestamp: number
	workspaceRoot: string
	fileCount: number
	totalLOC: number
	analyzedExtensions: string[]
	durationMs: number
}

// ============================================================================
// ClusterGraph - LLM Clustering Output
// ============================================================================

/**
 * C4 Component Types (Level 3 - Component Diagram)
 * See: https://c4model.com/
 */
export type C4ComponentType =
	| "controller" // HTTP request handlers, API routes
	| "service" // Business logic, orchestration
	| "repository" // Data access layer
	| "component" // UI component (React, Vue, etc.)
	| "gateway" // External API client
	| "database" // Database schema, ORM models
	| "external_system" // Third-party integrations
	| "message_queue" // Event queue, message broker
	| "cache" // Cache layer (Redis, etc.)
	| "middleware" // Request/response middleware
	| "utility" // Helper functions, utilities
	| "config" // Configuration management

/**
 * C4 Relationship Types
 */
export type C4RelationshipType =
	| "uses" // Generic usage
	| "calls" // Synchronous invocation
	| "renders" // UI rendering
	| "reads_from" // Data read operation
	| "writes_to" // Data write operation
	| "publishes_to" // Message publishing
	| "subscribes_to" // Message subscription

/**
 * Communication Protocols
 */
export type C4Protocol = "HTTP" | "gRPC" | "SQL" | "Redis" | "REST" | "GraphQL" | "WebSocket" | "AMQP" | "Internal" // In-process call

/**
 * Technology Stack for a component
 */
export interface TechnologyStack {
	language?: string // e.g., "TypeScript", "JavaScript"
	framework?: string // e.g., "React", "Express", "NestJS"
	libraries?: string[] // Top 3-5 libraries (e.g., ["axios", "zod", "rxjs"])
	databases?: string[] // e.g., ["PostgreSQL", "Redis"]
	messaging?: string[] // e.g., ["Kafka", "RabbitMQ"]
}

/**
 * High-level architectural diagram with files grouped into clusters.
 * Generated by ArchitectureClusteringService using LLM.
 */
export interface ClusterGraph {
	id?: string // Generated programmatically after LLM generation
	name?: string // LLM-generated descriptive name for the diagram
	clusters: Cluster[] // 5-12 architectural components
	clusterEdges: ClusterEdge[]
	filteringDefaults: FilteringDefaults
	metadata?: ClusterGraphMetadata // Added programmatically after LLM generation
}

/**
 * A cluster representing an architectural component (e.g., "auth-layer").
 */
export interface Cluster {
	id: string // Lowercase-with-hyphens (e.g., "auth-layer")
	label: string // Human-readable (e.g., "Authentication Layer")
	description: string // LLM-generated 1-2 sentence summary
	files: string[] // File paths (MUST exist in inventory)
	keyFiles: string[] // 3-5 most important files (evidence)
	color?: string // Hex color for visual distinction
	layer?: "presentation" | "business" | "data" | "infrastructure" // @deprecated Use componentType instead
	// C4 Model Fields (Version 2)
	version?: number // 1 = legacy layer-based, 2 = C4 component-based
	componentType?: C4ComponentType // C4 component classification
	technology?: TechnologyStack // Technology stack used by this component
	responsibilities?: string[] // 2-5 key responsibilities
}

/**
 * Directed edge between two clusters showing dependency relationship.
 */
export interface ClusterEdge {
	id: string
	source: string // Cluster ID (must reference valid cluster)
	target: string // Cluster ID
	weight: number // Sum of file→file dependency counts
	label: string // Edge description (e.g., "API calls")
	topDependencies: {
		// Top 3 file pairs driving this edge
		from: string
		to: string
		count: number
	}[]
	// C4 Model Fields (Version 2)
	relationshipType?: C4RelationshipType // Type of relationship (calls, uses, etc.)
	protocol?: C4Protocol // Communication protocol
	description?: string // Human-readable relationship description
}

/**
 * Default filtering and display settings for the diagram.
 */
export interface FilteringDefaults {
	minEdgeWeight: number // Hide edges below threshold (default: 2)
	collapsedClusters: string[] // Start collapsed
	visibleLayers: string[] // If using layers
}

/**
 * Metadata about cluster graph generation.
 */
export interface ClusterGraphMetadata {
	timestamp: number
	clusterCount: number
	sourceInventoryHash: string // Detect stale clusters
	schemaVersion?: number // 1 = legacy, 2 = C4
	c4Level?: "C3" // C4 model level (Component diagram)
}

// ============================================================================
// Diagram Actions - Chat-Driven Interactions
// ============================================================================

/**
 * Actions the LLM can take to interact with the diagram.
 */
export type DiagramAction =
	| { type: "highlight"; nodeIds: string[]; duration?: number }
	| { type: "filter"; edgeTypes?: string[]; minWeight?: number; clusterIds?: string[] }
	| { type: "expand"; clusterId: string } // Show files within cluster
	| { type: "focus"; nodeId: string } // Center + zoom

// ============================================================================
// Storage & Persistence
// ============================================================================

/**
 * Metadata about a saved cluster graph.
 */
export interface ClusterGraphInfo {
	id: string
	name?: string // LLM-generated descriptive name
	createdAt: number
	clusterCount: number
	fileCount: number
}

// ============================================================================
// Component Execution Tracing
// ============================================================================

/**
 * Execution trace through a component diagram.
 * Shows step-by-step flow with code references and example data.
 */
export interface ComponentExecutionTrace {
	id: string // Unique ID (trace_[timestamp]_[random])
	baseDiagramId: string // References ClusterGraph.id
	name?: string // LLM-generated descriptive name for the trace
	entryPoint: string // Natural language starting point (e.g., "User clicks Save button")
	steps: ExecutionStep[] // Sequential execution steps
	highlightedComponents: string[] // Component IDs to highlight
	animatedEdges: AnimatedEdge[] // Edges to animate (in order)
	metadata: ExecutionTraceMetadata
}

/**
 * A single execution step in the trace.
 */
export interface ExecutionStep {
	stepNumber: number // 1, 2, 3, ...
	componentId: string // Cluster ID from base diagram (validated)
	description: string // What happens at this step (2-3 sentences)
	codeReference: CodeReference // File path + line number
	exampleData: ExampleData // Data structure at this step
	transitionTo: string | null // Next component ID, or null if final step
}

/**
 * Reference to a specific location in code.
 */
export interface CodeReference {
	filePath: string // Relative to workspace root
	lineNumber?: number // Optional line number
	snippet?: string // Optional 3-5 line code excerpt
}

/**
 * Example data at a specific execution step.
 */
export interface ExampleData {
	format: string // "JSON", "SQL Query", "HTTP Request", etc.
	sample: string // Actual data example
}

/**
 * Animated edge in execution trace visualization.
 */
export interface AnimatedEdge {
	edgeId: string // ClusterEdge.id from base diagram
	animationOrder: number // 1, 2, 3, ... (display sequence)
	durationMs?: number // Optional: animation duration (default: 1000ms)
}

/**
 * Metadata about the execution trace.
 */
export interface ExecutionTraceMetadata {
	timestamp: number // When trace was created
	totalSteps: number // Number of execution steps
	componentsInvolved: number // Number of unique components
}

/**
 * Summary information about a saved execution trace.
 */
export interface ExecutionTraceInfo {
	id: string
	baseDiagramId: string
	name?: string // LLM-generated descriptive name
	entryPoint: string
	createdAt: number
	stepCount: number
}
