/**
 * Type definitions for architecture visualization feature.
 *
 * This module defines two core data structures:
 * 1. RepoInventory - Deterministic analysis output from ts-morph
 * 2. ClusterGraph - LLM-generated clustering of files into architectural components
 */

// ============================================================================
// RepoInventory - Deterministic Analysis Output
// ============================================================================

/**
 * Complete inventory of a repository's structure and dependencies.
 * Generated by ArchitectureAnalysisService from AST parsing.
 */
export interface RepoInventory {
	files: FileRecord[] // All analyzed TypeScript/JavaScript files
	dependencies: DependencyEdge[] // file→file import graph
	metadata: InventoryMetadata
}

/**
 * Record of a single analyzed file with exports and imports.
 */
export interface FileRecord {
	path: string // Relative to workspace root
	size: number // Bytes
	linesOfCode: number
	exports: ExportedSymbol[] // Functions, classes, types exported
	imports: ImportRecord[] // What this file imports
	language: "typescript" | "javascript"
}

/**
 * A symbol exported from a file (function, class, interface, etc.)
 */
export interface ExportedSymbol {
	name: string
	kind: "function" | "class" | "interface" | "type" | "const" | "enum" | "variable"
	isDefault: boolean
}

/**
 * Import statement parsed from a file.
 */
export interface ImportRecord {
	source: string // Module path (relative or package)
	resolvedPath?: string // Resolved file path (if local)
	importedSymbols: string[] // What's imported
	isTypeOnly: boolean
}

/**
 * Directed edge representing a file→file dependency.
 */
export interface DependencyEdge {
	from: string // Source file path
	to: string // Target file path
	count: number // Number of import statements
	importedTypes: string[] // Symbol kinds imported
}

/**
 * Metadata about the analysis run.
 */
export interface InventoryMetadata {
	timestamp: number
	workspaceRoot: string
	fileCount: number
	totalLOC: number
	analyzedExtensions: string[]
	durationMs: number
}

// ============================================================================
// ClusterGraph - LLM Clustering Output
// ============================================================================

/**
 * High-level architectural diagram with files grouped into clusters.
 * Generated by ArchitectureClusteringService using LLM.
 */
export interface ClusterGraph {
	id?: string // Generated programmatically after LLM generation
	clusters: Cluster[] // 5-12 architectural components
	clusterEdges: ClusterEdge[]
	filteringDefaults: FilteringDefaults
	metadata?: ClusterGraphMetadata // Added programmatically after LLM generation
}

/**
 * A cluster representing an architectural component (e.g., "auth-layer").
 */
export interface Cluster {
	id: string // Lowercase-with-hyphens (e.g., "auth-layer")
	label: string // Human-readable (e.g., "Authentication Layer")
	description: string // LLM-generated 1-2 sentence summary
	files: string[] // File paths (MUST exist in inventory)
	keyFiles: string[] // 3-5 most important files (evidence)
	color?: string // Hex color for visual distinction
	layer?: "presentation" | "business" | "data" | "infrastructure"
}

/**
 * Directed edge between two clusters showing dependency relationship.
 */
export interface ClusterEdge {
	id: string
	source: string // Cluster ID (must reference valid cluster)
	target: string // Cluster ID
	weight: number // Sum of file→file dependency counts
	label: string // Edge description (e.g., "API calls")
	topDependencies: {
		// Top 3 file pairs driving this edge
		from: string
		to: string
		count: number
	}[]
}

/**
 * Default filtering and display settings for the diagram.
 */
export interface FilteringDefaults {
	minEdgeWeight: number // Hide edges below threshold (default: 2)
	collapsedClusters: string[] // Start collapsed
	visibleLayers: string[] // If using layers
}

/**
 * Metadata about cluster graph generation.
 */
export interface ClusterGraphMetadata {
	timestamp: number
	clusterCount: number
	sourceInventoryHash: string // Detect stale clusters
}

// ============================================================================
// Diagram Actions - Chat-Driven Interactions
// ============================================================================

/**
 * Actions the LLM can take to interact with the diagram.
 */
export type DiagramAction =
	| { type: "highlight"; nodeIds: string[]; duration?: number }
	| { type: "filter"; edgeTypes?: string[]; minWeight?: number; clusterIds?: string[] }
	| { type: "expand"; clusterId: string } // Show files within cluster
	| { type: "focus"; nodeId: string } // Center + zoom

// ============================================================================
// Storage & Persistence
// ============================================================================

/**
 * Metadata about a saved cluster graph.
 */
export interface ClusterGraphInfo {
	id: string
	createdAt: number
	clusterCount: number
	fileCount: number
}
